game_club/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('game_clubs.urls')),
]

game_clubs/urls.py
from django.urls import path

from . import views

app_name = "game_clubs"

urlpatterns = [
    # Pages
    path('', views.index, name="index"),
    # Shows all games
    path('games/', views.games, name="games"),
    # Single game
    path('games/<int:game_id>/', views.game, name="game"),
    # New game
    path('new_game/', views.new_game, name="new_game"),
    # New loan
    path('new_loan/<int:game_id>/', views.new_loan, name="new_loan"),
    # Edit loan
    path('edit_loan/<int:loan_id>/', views.edit_loan, name="edit_loan"),
]

users/urls.py
from django import urls
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    
    path('', include('django.contrib.auth.urls')),
    # Registration
    path('register/', views.register, name='register'),

]

game_clubs/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User

# Create your models here.
class Game(models.Model):

    name = models.CharField(max_length=200)
    maker = models.JSONField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return f"{self.name} by {',' .join(self.maker)}."

class Review(models.Model):

    my_review = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.my_review[:50]}..."

class Loan(models.Model):

    my_loan = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.my_loan[:50]}.."

users/models.py
from django.db import models

# Create your models here.

game_clubs/forms.py
from django import forms
from django.forms import fields, widgets

from .models import Game, Loan

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'maker']

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['my_loan']
        widgets = {'my_loan' : forms.Textarea(attrs={'cols': 80})}

game_clubs/views.py
from django.shortcuts import redirect, render
from .models import Game, Loan
from .forms import GameForm, LoanForm
from django.http import Http404

# Create your views here.
def index(request):
    return render(request, "game_clubs/index.html")

def games(request):
    """Show all games"""
    games = Game.objects.order_by('date_added')
    context = {'games' : games}
    return render(request, 'game_clubs/games.html', context)

def game(request, game_id):
    """Show a single game and its review and loans"""
    game = Game.objects.get(id=game_id)
    loans = game.loan_set.order_by('-date_added')
    context = {'game':game, 'loans':loans}
    return render(request, 'game_clubs/game.html', context)

def new_game(request):
    """Add New Game"""
    if request.method != 'POST':
        #NO DATA SUBMITTED. CREATE A BLANK FORM
        form = GameForm()
    else:
        #POST DATA SUBMITTED. PROCESS DATA
        form = GameForm(data = request.POST)
        if form.is_valid():
            new_game = form.save(commit=False)
            new_game.owner = request.user
            new_game.save()
            return redirect('game_clubs:games') 

    context = {'form' : form}
    return render(request, 'game_clubs/new_game.html', context)

def new_loan(request, game_id):
    """Add new review for a book"""
    game = Game.objects.get(id=game_id)
    if request.method != 'POST':
        form = LoanForm()
    else:
        form = LoanForm(data=request.POST)
        if form.is_valid():
            new_loan = form.save(commit=False)
            new_loan.game = game
            new_loan.save()
            return redirect('game_clubs:game', game_id=game_id) 

    #Display blank or invalid form
    context = {'game' : game, 'form' : form}
    return render(request, 'game_clubs/new_loan.html', context)

def edit_loan(request, loan_id):
    loan = Loan.objects.get(id=loan_id)
    game = loan.game

    #Protecting edit loan page
    if game.owner != request.user:
       raise Http404

    if request.method != 'POST':
        form = LoanForm(instance=loan)
    else:
        form = LoanForm(instance=loan, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('game_clubs:game', game_id = game.id)

    context = {'loan' : loan, 'game' : game, 'form' : form}
    return render(request, 'game_clubs/edit_loan.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('game_clubs:index')

    context = { 'form' : form } 
    return render(request, 'registration/register.html', context)

game_clubs/templates/game_clubs/base.html
<p>
    <a href="{% url 'game_clubs:index' %}">Game Club</a> -
    <a href="{% url 'game_clubs:games' %}">Games</a> -
    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a> -
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

game_clubs/templates/game_clubs/edit_loan.html
{% extends "game_clubs/base.html" %}

{% block content %}

<p><a href="{% url 'game_clubs:game' game.id %}">{{ game }}</a></p>

<p>Edit loan:</p>

<form action="{% url 'game_clubs:edit_loan' loan.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

game_clubs/templates/game_clubs/game.html
{% extends "game_clubs/base.html" %}
{% block content %}

<p>Board Game: {{ game }}</p>


<p>Loan the game and give a estimate how long you are going to keep the board game</p>
<p>Remember to check that the game is available!</p>
<p>
<a href="{% url 'game_clubs:new_loan' game.id %}">Add new loan</a>
</p>
<p>Loans for the game:</p>
<ul>
{% for loan in loans %}
<li>
    <p>{{ loan.date_added|date:'M d, Y H:i' }}</p>
    <p>{{ loan.my_loan|linebreaks }}</p>
    <p>
    <a href="{% url 'game_clubs:edit_loan' loan.id %}">Edit loan</a>
    </p>   
</li>
{% empty %}
<li>No loans yet</li>
{% endfor %}
</ul>

{% endblock content %}

game_clubs/templates/game_clubs/games.html
{% extends "game_clubs/base.html" %}
{% block content %}

<p>Board Games</p>

<ul>
    {% for game in games %}
    <li><a href="{% url 'game_clubs:game' game.id %}">{{ game }}</a></li>
    {% empty %}
    <li>No board games here yet</li>
    {% endfor %}
</ul>

<a href="{% url 'game_clubs:new_game' %}">Add new game</a>

{% endblock content %}

game_clubs/templates/game_clubs/index.html
{% extends "game_clubs/base.html" %}
{% block content %}

<p>Game Club</p>
<p>A place for you to share and loan your favorite board games!</p>

{% endblock content %}

game_clubs/templates/game_clubs/new_game.html
{% extends "game_clubs/base.html" %}

{% block content %}
<p>Add new game:</p>

<form action="{% url 'game_clubs:new_game' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add game</button>
</form>

{% endblock content %}

game_clubs/templates/game_clubs/new_loan.html
{% extends "game_clubs/base.html" %}

{% block content %}

<p><a href="{% url 'game_clubs:game' game.id %}">{{ game }}</a></p>

<p>Add new loan</p>

<form action="{% url 'game_clubs:new_loan' game.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add loan</button>
</form>

{% endblock content %}